# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#

# Role.destroy_all
# Role.create!([
# 	{name_en: 'Root',name_fr: 'Super Admin',protected: 1,custom_role_id: 0},
# 	{name_en: 'IT Administrator',name_fr: 'Administrateur IT',protected: 1,custom_role_id: 1},
# 	{name_en: 'Manager',name_fr: 'Manager',protected: 1,custom_role_id: 2},
# 	{name_en: 'Internal Physician Supervisor',name_fr: 'Superviseur interne médecin',protected: 1,custom_role_id: 3},
# 	{name_en: 'Customer',name_fr: 'Client',protected: 1,custom_role_id: 4},
# 	{name_en: 'Delegated customer',name_fr: 'Client délégué',protected: 1,custom_role_id: 5},
# 	{name_en: 'Establishment administrator',name_fr: 'Administrateur établissement',protected: 1,custom_role_id: 6},
# 	{name_en: 'Service administrator',name_fr: 'Administrateur service',protected: 1,custom_role_id: 7},
# 	{name_en: 'Physician',name_fr: 'Prestataire médecin',protected: 1,custom_role_id: 8},
# 	{name_en: 'Technical Service Provider',name_fr: 'Prestataire technique',protected: 1,custom_role_id: 9},
# 	{name_en: 'Administrative staff',name_fr: 'Personnels administratifs',protected: 1,custom_role_id: 10},
# 	{name_en: 'Salesman before sale',name_fr: 'Commercial avant vente',protected: 1,custom_role_id: 11},
# 	{name_en: 'Salesman SAV',name_fr: 'Commercial SAV',protected: 1,custom_role_id: 12},
# 	{name_en: 'Patient',name_fr: 'Patient',protected: 1,custom_role_id: 13}])

# Permission.destroy_all
Permission.create!([
# 	{subject_class: 'Admin::BankAccounts',action: 'create',name_en: 'Create a Bank Account',description: 'nil',name_fr: "Créer un compte bancaire",title: "BankAccounts"},
# 	{subject_class: 'Admin::BankAccounts',action: 'index',name_en: 'Go to the directory of Bank Accounts',description: 'nil',name_fr: "Accédez au répertoire des comptes bancaires",title: "BankAccounts"},
# 	{subject_class: 'Admin::BankAccounts',action: 'search',name_en: 'Search Bank Accounts',description: 'nil',name_fr: "Rechercher dans les comptes bancaires",title: "BankAccounts"},
# 	{subject_class: 'Admin::BankAccounts',action: 'update',name_en: 'Update a Bank Account',description: 'nil',name_fr: "Mettre à jour un compte bancaire",title: "BankAccounts"},
# 	{subject_class: 'Admin::BankAccounts',action: 'destroy',name_en: 'Delete a Bank Account',description: 'nil',name_fr: "Supprimer un compte bancaire",title: "BankAccounts"},
# 	{subject_class: 'Admin::BankAccounts',action: 'show',name_en: 'Show a Bank Account',description: 'nil',name_fr: "Afficher un compte bancaire",title: "BankAccounts"},

# 	# {subject_class: 'Admin::Companies',action: 'create',name_en: 'Create a Company',description: 'nil',name_fr: "Créer une entreprise"},
# 	# {subject_class: 'Admin::Companies',action: 'index',name_en: 'Go to the directory of Companies',description: 'nil',name_fr: "Aller à l'annuaire des sociétés"},
# 	# {subject_class: 'Admin::Companies',action: 'search',name_en: 'Search Companies',description: 'nil',name_fr: "Recherche d'entreprises"},
# 	# {subject_class: 'Admin::Companies',action: 'update',name_en: 'Update a Company',description: 'nil',name_fr: "Mettre à jour une entreprise"},
# 	# {subject_class: 'Admin::Companies',action: 'destroy',name_en: 'Delete a Company',description: 'nil',name_fr: "Supprimer une entreprise"},
# 	# {subject_class: 'Admin::Companies',action: 'show',name_en: 'Show a Company',description: 'nil',name_fr: "Afficher une entreprise"},

# 	{subject_class: 'Admin::Equipment',action: 'create',name_en: 'Create an Equipment',description: 'nil',name_fr: "Créer un équipement",title: "Equipment"},
# 	{subject_class: 'Admin::Equipment',action: 'index',name_en: 'Go to the directory of Equipment',description: 'nil',name_fr: "Aller à l'annuaire de l'équipement",title: "Equipment"},
# 	{subject_class: 'Admin::Equipment',action: 'search',name_en: 'Search Equipment',description: 'nil',name_fr: "Équipement de recherche",title: "Equipment"},
# 	{subject_class: 'Admin::Equipment',action: 'update',name_en: 'Update an Equipment',description: 'nil',name_fr: "Mettre à jour un équipement",title: "Equipment"},
# 	{subject_class: 'Admin::Equipment',action: 'destroy',name_en: 'Delete an Equipment',description: 'nil',name_fr: "Supprimer un équipement",title: "Equipment"},
# 	{subject_class: 'Admin::Equipment',action: 'show',name_en: 'Show an Equipment',description: 'nil',name_fr: "Afficher un équipement",title: "Equipment"},
# 	{subject_class: 'Admin::Equipment',action: 'export_equipment_list',name_en: 'Export Equipment list',description: 'nil',name_fr: "Liste d'équipement d'exportation",title: "Equipment"},

# 	{subject_class: 'Admin::EquipmentBrands',action: 'create',name_en: 'Create an Equipment Brand',description: 'nil',name_fr: "Créer une marque d'équipement",title: "EquipmentBrands"},
# 	{subject_class: 'Admin::EquipmentBrands',action: 'index',name_en: 'Go to the directory of Equipment Brands',description: 'nil',name_fr: "Accéder à l'annuaire des marques d'équipements",title: "EquipmentBrands"},
# 	{subject_class: 'Admin::EquipmentBrands',action: 'search',name_en: 'Search Equipment Brand',description: 'nil',name_fr: "Marque de l'équipement de recherche",title: "EquipmentBrands"},
# 	{subject_class: 'Admin::EquipmentBrands',action: 'update',name_en: 'Update an Equipment Brand',description: 'nil',name_fr: "Mettre à jour une marque d'équipement",title: "EquipmentBrands"},
# 	{subject_class: 'Admin::EquipmentBrands',action: 'destroy',name_en: 'Delete an Equipment Brand',description: 'nil',name_fr: "Supprimer une marque d'équipement",title: "EquipmentBrands"},
# 	{subject_class: 'Admin::EquipmentBrands',action: 'show',name_en: 'Show an Equipment Brand',description: 'nil',name_fr: "Afficher une marque de matériel",title: "EquipmentBrands"},

# 	{subject_class: 'Admin::EquipmentModels',action: 'create',name_en: 'Create an Equipment Model',description: 'nil',name_fr: "Créer un modèle d'équipement",title: "EquipmentModels"},
# 	{subject_class: 'Admin::EquipmentModels',action: 'index',name_en: 'Go to the directory of Equipment Models',description: 'nil',name_fr: "Aller au répertoire des modèles d'équipement",title: "EquipmentModels"},
# 	{subject_class: 'Admin::EquipmentModels',action: 'search',name_en: 'Search Equipment Model',description: 'nil',name_fr: "Modèle d'équipement de recherche",title: "EquipmentModels"},
# 	{subject_class: 'Admin::EquipmentModels',action: 'update',name_en: 'Update an Equipment Model',description: 'nil',name_fr: "Mettre à jour un modèle d'équipement",title: "EquipmentModels"},
# 	{subject_class: 'Admin::EquipmentModels',action: 'destroy',name_en: 'Delete an Equipment Model',description: 'nil',name_fr: "Supprimer un modèle d'équipement",title: "EquipmentModels"},
# 	{subject_class: 'Admin::EquipmentModels',action: 'show',name_en: 'Show an Equipment Model',description: 'nil',name_fr: "Afficher un modèle d'équipement",title: "EquipmentModels"},

# 	{subject_class: 'Admin::EquipmentTypes',action: 'create',name_en: 'Create an Equipment Type',description: 'nil',name_fr: "Créer un type d'équipement",title: "EquipmentTypes"},
# 	{subject_class: 'Admin::EquipmentTypes',action: 'index',name_en: 'Go to the directory of Equipment Types',description: 'nil',name_fr: "Accéder au répertoire des types d'équipement",title: "EquipmentTypes"},
# 	{subject_class: 'Admin::EquipmentTypes',action: 'search',name_en: 'Search Equipment Type',description: 'nil',name_fr: "Rechercher Type d'équipement",title: "EquipmentTypes"},
# 	{subject_class: 'Admin::EquipmentTypes',action: 'update',name_en: 'Update an Equipment Type',description: 'nil',name_fr: "Mettre à jour un type d'équipement",title: "EquipmentTypes"},
# 	{subject_class: 'Admin::EquipmentTypes',action: 'destroy',name_en: 'Delete an Equipment Type',description: 'nil',name_fr: "Supprimer un type d'équipement",title: "EquipmentTypes"},
# 	{subject_class: 'Admin::EquipmentTypes',action: 'show',name_en: 'Show an Equipment Type',description: 'nil',name_fr: "Afficher un type d'équipement",title: "EquipmentTypes"},

# 	{subject_class: 'Admin::Establishments',action: 'create',name_en: 'Create a business',description: 'nil',name_fr: "Créer un établissement",title: "Establishments"},
# 	{subject_class: 'Admin::Establishments',action: 'index',name_en: 'Go to the directory of establishments',description: 'nil',name_fr: "Accéder à l'annuaire des établissements",title: "Establishments"},
# 	{subject_class: 'Admin::Establishments',action: 'search',name_en: 'Search Institutions',description: 'nil',name_fr: 'Rechercher des établissements',title: "Establishments"},
# 	{subject_class: 'Admin::Establishments',action: 'update',name_en: 'Update a property change',description: 'nil',name_fr: 'Modifier Niveau abonnement établissement',title: "Establishments"},
# 	{subject_class: 'Admin::Establishments',action: 'destroy',name_en: 'Delete an institution',description: 'nil',name_fr: 'Supprimer un établissement',title: "Establishments"},
# 	{subject_class: 'Admin::Establishments',action: 'show',name_en: 'View property details',description: 'nil',name_fr: 'Consulter fiche établissement',title: "Establishments"},

#  	{subject_class: 'Admin::EstablishmentServices',action: 'create',name_en: 'Create a service',description: 'nil',name_fr: "Créer un service",title: "EstablishmentServices"},
# 	{subject_class: 'Admin::EstablishmentServices',action: 'index',name_en: 'Access the service directory',description: 'nil',name_fr: "Accéder à l'annuaire des établissements",title: "EstablishmentServices"},
# 	{subject_class: 'Admin::EstablishmentServices',action: 'update',name_en: 'Update a service modification',description: 'nil',name_fr: 'Mettre à jour une modification de service',title: "EstablishmentServices"},
# 	{subject_class: 'Admin::EstablishmentServices',action: 'destroy',name_en: 'Delete a service',description: 'nil',name_fr: 'Supprimer un service',title: "EstablishmentServices"},

# 	{subject_class: 'Admin::Plans',action: 'create',name_en: 'Create a Plan',description: 'nil',name_fr: "Créer un plan",title: "Plans"},
# 	{subject_class: 'Admin::Plans',action: 'index',name_en: 'Go to the directory of Plans',description: 'nil',name_fr: "Aller au répertoire des Plans",title: "Plans"},
# 	{subject_class: 'Admin::Plans',action: 'search',name_en: 'Search Plan',description: 'nil',name_fr: "Plan de recherche",title: "Plans"},
# 	{subject_class: 'Admin::Plans',action: 'update',name_en: 'Update a Plan',description: 'nil',name_fr: "Mettre à jour un plan",title: "Plans"},
# 	{subject_class: 'Admin::Plans',action: 'destroy',name_en: 'Delete a Plan',description: 'nil',name_fr: "Supprimer un plan",title: "Plans"},
# 	{subject_class: 'Admin::Plans',action: 'show',name_en: 'Show a Plan',description: 'nil',name_fr: "Afficher un plan",title: "Plans"},

# 	{subject_class: 'Admin::Positions',action: 'create',name_en: 'Create a Position',description: 'nil',name_fr: "Créer une position",title: "Positions"},
# 	{subject_class: 'Admin::Positions',action: 'index',name_en: 'Go to the directory of Positions',description: 'nil',name_fr: "Allez dans le répertoire des postes",title: "Positions"},
# 	{subject_class: 'Admin::Positions',action: 'search',name_en: 'Search Position',description: 'nil',name_fr: "Recherche Position",title: "Positions"},
# 	{subject_class: 'Admin::Positions',action: 'update',name_en: 'Update a Position',description: 'nil',name_fr: "Mettre à jour une position",title: "Positions"},
# 	{subject_class: 'Admin::Positions',action: 'destroy',name_en: 'Delete a Position',description: 'nil',name_fr: "Supprimer une position",title: "Positions"},
# 	{subject_class: 'Admin::Positions',action: 'show',name_en: 'Show a Position',description: 'nil',name_fr: "Afficher une position",title: "Positions"},

# 	{subject_class: 'Admin::Roles',action: 'create',name_en: 'Create a Role',description: 'nil',name_fr: "Créer un rôle",title: "Roles"},
# 	{subject_class: 'Admin::Roles',action: 'index',name_en: 'Go to the directory of Roles',description: 'nil',name_fr: "Aller au répertoire des Rôles",title: "Roles"},
# 	{subject_class: 'Admin::Roles',action: 'search',name_en: 'Search Role',description: 'nil',name_fr: "Rechercher un rôle",title: "Roles"},
# 	{subject_class: 'Admin::Roles',action: 'update',name_en: 'Update a Role',description: 'nil',name_fr: "Mettre à jour un rôle",title: "Roles"},
# 	{subject_class: 'Admin::Roles',action: 'destroy',name_en: 'Delete a Role',description: 'nil',name_fr: "Supprimer un rôle",title: "Roles"},
# 	{subject_class: 'Admin::Roles',action: 'show',name_en: 'Show a Role',description: 'nil',name_fr: "Afficher un rôle",title: "Roles"},

# 	{subject_class: 'Admin::Skills',action: 'create',name_en: 'Create a Skill',description: 'nil',name_fr: "Créer une compétence",title: "Skills"},
# 	{subject_class: 'Admin::Skills',action: 'index',name_en: 'Go to the directory of Skills',description: 'nil',name_fr: "Accéder au répertoire des compétences",title: "Skills"},
# 	{subject_class: 'Admin::Skills',action: 'search',name_en: 'Search Skill',description: 'nil',name_fr: "Recherche compétence",title: "Skills"},
# 	{subject_class: 'Admin::Skills',action: 'update',name_en: 'Update a Skill',description: 'nil',name_fr: "Mettre à jour une compétence",title: "Skills"},
# 	{subject_class: 'Admin::Skills',action: 'destroy',name_en: 'Delete a Skill',description: 'nil',name_fr: "Supprimer une compétence",title: "Skills"},
# 	{subject_class: 'Admin::Skills',action: 'show',name_en: 'Show a Skill',description: 'nil',name_fr: "Afficher une compétence",title: "Skills"},

# 	{subject_class: 'Admin::Specialities',action: 'create',name_en: 'Create a Speciality',description: 'nil',name_fr: "Créer une spécialité",title: "Specialities"},
# 	{subject_class: 'Admin::Specialities',action: 'index',name_en: 'Go to the directory of Specialities',description: 'nil',name_fr: "Aller à l'annuaire des Spécialités",title: "Specialities"},
# 	{subject_class: 'Admin::Specialities',action: 'search',name_en: 'Search Speciality',description: 'nil',name_fr: "Rechercher Spécialité",title: "Specialities"},
# 	{subject_class: 'Admin::Specialities',action: 'update',name_en: 'Update a Speciality',description: 'nil',name_fr: "Mettre à jour une spécialité",title: "Specialities"},
# 	{subject_class: 'Admin::Specialities',action: 'destroy',name_en: 'Delete a Speciality',description: 'nil',name_fr: "Supprimer une spécialité",title: "Specialities"},
# 	{subject_class: 'Admin::Specialities',action: 'show',name_en: 'Show a Speciality',description: 'nil',name_fr: "Afficher une spécialité",title: "Specialities"},

# 	{subject_class: 'Admin::Users',action: 'pre_creation_user',name_en: 'Pre creation of user',description: 'nil',name_fr: 'Utilisateur pré-création',title: "Users"},
#   {subject_class: 'Admin::Users',action: 'create',name_en: 'creation of user',description: 'nil',name_fr: 'Création dutilisateur',title: "Users"},
#   {subject_class: 'Admin::Users',action: 'index',name_en: 'show user list',description: 'nil',name_fr: 'Afficher la liste des utilisateurs',title: "Users"},
#   {subject_class: 'Admin::Users',action: 'search',name_en: 'search user',description: 'nil',name_fr: 'Rechercher un utilisateur',title: "Users"},
#   {subject_class: 'Admin::Users',action: 'update',name_en: 'updation of user',description: 'nil',name_fr: 'Mise à jour de lutilisateur',title: "Users"},
#   {subject_class: 'Admin::Users',action: 'destroy',name_en: 'delete user',description: 'nil',name_fr: 'Supprimer lutilisateur',title: "Users"},
#   {subject_class: 'Admin::Users',action: 'accounts_to_active',name_en: 'Access the list of accounts to activate',description: 'nil',name_fr: 'Accéder à la liste des comptes à activer',title: "Users"},
#   {subject_class: 'Admin::Users',action: 'active_user_account',name_en: 'Activate an account',description: 'nil',name_fr: 'Activer un compte',title: "Users"},

#   {subject_class: 'Users::Registrations',action: 'edit',name_en: 'Access your personal profile',description: 'nil',name_fr: 'Accédez à votre profil personnel',title: "Other"},
#   {subject_class: 'Users::Registrations',action: 'update',name_en: 'Edit personal profile',description: 'nil',name_fr: 'Modifier le profil personnel',title: "Other"},

# 	{subject_class: 'nil',action: 'nil',name_en: 'Set Chrono file ',description: 'nil',name_fr: "Définir le fichier Chrono",title: "Administration"},
# 	{subject_class: 'nil',action: 'nil',name_en: 'Set Waiting time',description: 'ni',name_fr: "Définir le temps d'attente",title: "Administration"},
# 	{subject_class: 'nil',action: 'nil',name_en: 'Reassignment pending requests',description: 'nil',name_fr: "Rechercher dans les comptes bancaires",title: "Administration"},
# 	{subject_class: 'nil',action: 'nil',name_en: 'Set File Settings',description: 'nil',name_fr: "Définir les paramètres de fichier",title: "Administration"},
# 	{subject_class: 'nil',action: 'nil',name_en: 'Set all delays',description: 'nil',name_fr: "Régler tous les retards",title: "Administration"},
# 	{subject_class: 'nil',action: 'nil',name_en: 'Upgrade establishment subscription',description: 'nil',name_fr: "Abonnement à l'établissement de mise à niveau",title: "Administration"},
# 	{subject_class: 'nil',action: 'nil',name_en: 'Switch Salesman perimeter',description: 'nil',name_fr: "Périmètre commutateur vendeur",title: "Administration"},
# 	{subject_class: 'nil',action: 'nil',name_en: 'View dashboard activity',description: 'nil',name_fr: "Afficher l'activité du tableau de bord
# ",title: "Administration"},


  # {subject_class: 'Admin::Patients',action: 'create',name_en: 'creation of form',description: 'nil',name_fr: 'Création de formulaire',title: "Upload_File"},
  {subject_class: 'Admin::Forms',action: 'index',name_en: 'Go to the directory of Forms',description: 'nil',name_fr: 'Accéder au répertoire des formulaires',title: "Upload_File"},
  {subject_class: 'Admin::Forms',action: 'search',name_en: 'search form',description: 'nil',name_fr: 'Formulaire de recherche',title: "Upload_File"},
  {subject_class: 'Admin::Forms',action: 'update',name_en: 'updation of form',description: 'nil',name_fr: 'Mise à jour du formulaire',title: "Upload_File"},
  {subject_class: 'Admin::Forms',action: 'destroy',name_en: 'delete form',description: 'nil',name_fr: 'Supprimer le formulaire',title: "Upload_File"},
  {subject_class: 'Admin::Forms',action: 'show',name_en: 'show form',description: 'nil',name_fr: 'Montrer le formulaire',title: "Upload_File"},

	])

	# Setting.destroy_all
	# Setting.create!([
	# 	{ user_type: 1, price: 400.00,file_type: 1,workflow_type: 1,payment_type: 1,billing_price: 25.00,payment_waiting_delay: 2,analysis_delay: 1 },
	# 	{ user_type: 2, price: 500.00,file_type: 2,workflow_type: 2,payment_type: 2,billing_price: 30.00,payment_waiting_delay: 3,analysis_delay: 2 }
	# ])

	@company_permissions = Permission.where(subject_class: "Admin::Companies")

	@company_permissions.each do |company_permission|
		@role_permissions = RolePermission.where(permission_id: company_permission.id)
		@role_permissions.each do |role_permission|
			role_permission.destroy
		end
	end

	@company_permissions.each do |company_permi|
		company_permi.destroy
	end

# Country.destroy_all
# Country.create!([
# 	{ name: "Algeria", country_code: "DZ", telephone_code: "213" },
#   { name: "Andorra", country_code: "AD", telephone_code: "376" },
#   { name: "Angola", country_code: "AO", telephone_code: "244" },
#   { name: "Anguilla", country_code: "AI", telephone_code: "1264" },
#   { name: "Antigua & Barbuda", country_code: "AG", telephone_code: "1268" },
#   { name: "Argentina", country_code: "AR", telephone_code: "54" },
#   { name: "Armenia", country_code: "AM", telephone_code: "374" },
#   { name: "Aruba", country_code: "AW", telephone_code: "297" },
#   { name: "Australia", country_code: "AU", telephone_code: "61" },
#   { name: "Austria", country_code: "AT", telephone_code: "43" },
#   { name: "Azerbaijan", country_code: "AZ", telephone_code: "994" },
#   { name: "Bahamas", country_code: "BS", telephone_code: "1242" },
#   { name: "Bahrain", country_code: "BH", telephone_code: "973" },
#   { name: "Bangladesh", country_code: "BD", telephone_code: "880" },
#   { name: "Barbados", country_code: "BB", telephone_code: "1246" },
#   { name: "Belarus", country_code: "BY", telephone_code: "375" },
#   { name: "Belgium", country_code: "BE", telephone_code: "32" },
#   { name: "Belize", country_code: "BZ", telephone_code: "501" },
#   { name: "Benin", country_code: "BJ", telephone_code: "229" },
#   { name: "Bermuda", country_code: "BM", telephone_code: "1441" },
#   { name: "Bhutan", country_code: "BT", telephone_code: "975" },
#   { name: "Bolivia", country_code: "BO", telephone_code: "591" },
#   { name: "Bosnia Herzegovina", country_code: "BA", telephone_code: "387" },
#   { name: "Botswana", country_code: "BW", telephone_code: "267" },
#   { name: "Brazil", country_code: "BR", telephone_code: "55" },
#   { name: "Brunei", country_code: "BN", telephone_code: "673" },
#   { name: "Bulgaria", country_code: "BG", telephone_code: "359" },
#   { name: "Burkina Faso", country_code: "BF", telephone_code: "226" },
#   { name: "Burundi", country_code: "BI", telephone_code: "257" },
#   { name: "Cambodia", country_code: "KH", telephone_code: "855" },
#   { name: "Cameroon", country_code: "CM", telephone_code: "237" },
#   { name: "Canada", country_code: "CA", telephone_code: "1" },
#   { name: "Cape Verde Islands", country_code: "CV", telephone_code: "238" },
#   { name: "Cayman Islands", country_code: "KY", telephone_code: "1345" },
#   { name: "Central African Republic", country_code: "CF", telephone_code: "236" },
#   { name: "Chile", country_code: "CL", telephone_code: "56" },
#   { name: "China", country_code: "CN", telephone_code: "86" },
#   { name: "Colombia", country_code: "CO", telephone_code: "57" },
#   { name: "Comoros", country_code: "KM", telephone_code: "269" },
#   { name: "Congo", country_code: "CG", telephone_code: "242" },
#   { name: "Cook Islands", country_code: "CK", telephone_code: "682" },
#   { name: "Costa Rica", country_code: "CR", telephone_code: "506" },
#   { name: "Croatia", country_code: "HR", telephone_code: "385" },
#   { name: "Cuba", country_code: "CU", telephone_code: "53" },
#   { name: "Cyprus North", country_code: "CY", telephone_code: "90392" },
#   { name: "Cyprus South", country_code: "CY", telephone_code: "357" },
#   { name: "Czech Republic", country_code: "CZ", telephone_code: "42" },
#   { name: "Denmark", country_code: "DK", telephone_code: "45" },
#   { name: "Djibouti", country_code: "DJ", telephone_code: "253" },
#   { name: "Dominica", country_code: "DM", telephone_code: "1809" },
#   { name: "Dominican Republic", country_code: "DO", telephone_code: "1809" },
#   { name: "Ecuador", country_code: "EC", telephone_code: "593" },
#   { name: "Egypt", country_code: "EG", telephone_code: "20" },
#   { name: "El Salvador", country_code: "SV", telephone_code: "503" },
#   { name: "Equatorial Guinea", country_code: "GQ", telephone_code: "240" },
#   { name: "Eritrea", country_code: "ER", telephone_code: "291" },
#   { name: "Estonia", country_code: "EE", telephone_code: "372" },
#   { name: "Ethiopia", country_code: "ET", telephone_code: "251" },
#   { name: "Falkland Islands", country_code: "FK", telephone_code: "500" },
#   { name: "Faroe Islands", country_code: "FO", telephone_code: "298" },
#   { name: "Fiji", country_code: "FJ", telephone_code: "679" },
#   { name: "Finland", country_code: "FI", telephone_code: "358" },
#   { name: "France", country_code: "FR", telephone_code: "33" },
#   { name: "French Guiana", country_code: "GF", telephone_code: "594" },
#   { name: "French Polynesia", country_code: "PF", telephone_code: "689" },
#   { name: "Gabon", country_code: "GA", telephone_code: "241" },
#   { name: "Gambia", country_code: "GM", telephone_code: "220" },
#   { name: "Georgia", country_code: "GE", telephone_code: "7880" },
#   { name: "Germany", country_code: "DE", telephone_code: "49" },
#   { name: "Ghana", country_code: "GH", telephone_code: "233" },
#   { name: "Gibraltar", country_code: "GI", telephone_code: "350" },
#   { name: "Greece", country_code: "GR", telephone_code: "30" },
#   { name: "Greenland", country_code: "GL", telephone_code: "299" },
#   { name: "Grenada", country_code: "GD", telephone_code: "1473" },
#   { name: "Guadeloupe", country_code: "GP", telephone_code: "590" },
#   { name: "Guam", country_code: "GU", telephone_code: "671" },
#   { name: "Guatemala", country_code: "GT", telephone_code: "502" },
#   { name: "Guinea", country_code: "GN", telephone_code: "224" },
#   { name: "Guinea - Bissau", country_code: "GW", telephone_code: "245" },
#   { name: "Guyana", country_code: "GY", telephone_code: "592" },
#   { name: "Haiti", country_code: "HT", telephone_code: "509" },
#   { name: "Honduras", country_code: "HN", telephone_code: "504" },
#   { name: "Hong Kong", country_code: "HK", telephone_code: "852" },
#   { name: "Hungary", country_code: "HU", telephone_code: "36" },
#   { name: "Iceland", country_code: "IS", telephone_code: "354" },
#   { name: "India", country_code: "IN", telephone_code: "91" },
#   { name: "Indonesia", country_code: "ID", telephone_code: "62" },
#   { name: "Iran", country_code: "IR", telephone_code: "98" },
#   { name: "Iraq", country_code: "IQ", telephone_code: "964" },
#   { name: "Ireland", country_code: "IE", telephone_code: "353" },
#   { name: "Israel", country_code: "IL", telephone_code: "972" },
#   { name: "Italy", country_code: "IT", telephone_code: "39" },
#   { name: "Jamaica", country_code: "JM", telephone_code: "1876" },
#   { name: "Japan", country_code: "JP", telephone_code: "81" },
#   { name: "Jordan", country_code: "JO", telephone_code: "962" },
#   { name: "Kazakhstan", country_code: "KZ", telephone_code: "7" },
#   { name: "Kenya", country_code: "KE", telephone_code: "254" },
#   { name: "Kiribati", country_code: "KI", telephone_code: "686" },
#   { name: "Korea North", country_code: "KP", telephone_code: "850" },
#   { name: "Korea South", country_code: "KR", telephone_code: "82" },
#   { name: "Kuwait", country_code: "KW", telephone_code: "965" },
#   { name: "Kyrgyzstan", country_code: "KG", telephone_code: "996" },
#   { name: "Laos", country_code: "LA", telephone_code: "856" },
#   { name: "Latvia", country_code: "LV", telephone_code: "371" },
#   { name: "Lebanon", country_code: "LB", telephone_code: "961" },
#   { name: "Lesotho", country_code: "LS", telephone_code: "266" },
#   { name: "Liberia", country_code: "LR", telephone_code: "231" },
#   { name: "Libya", country_code: "LY", telephone_code: "218" },
#   { name: "Liechtenstein", country_code: "LI", telephone_code: "417" },
#   { name: "Lithuania", country_code: "LT", telephone_code: "370" },
#   { name: "Luxembourg", country_code: "LU", telephone_code: "352" },
#   { name: "Macao", country_code: "MO", telephone_code: "853" },
#   { name: "Macedonia", country_code: "MK", telephone_code: "389" },
#   { name: "Madagascar", country_code: "MG", telephone_code: "261" },
#   { name: "Malawi", country_code: "MW", telephone_code: "265" },
#   { name: "Malaysia", country_code: "MY", telephone_code: "60" },
#   { name: "Maldives", country_code: "MV", telephone_code: "960" },
#   { name: "Mali", country_code: "ML", telephone_code: "223" },
#   { name: "Malta", country_code: "MT", telephone_code: "356" },
#   { name: "Marshall Islands", country_code: "MH", telephone_code: "692" },
#   { name: "Martinique", country_code: "MQ", telephone_code: "596" },
#   { name: "Mauritania", country_code: "MR", telephone_code: "222" },
#   { name: "Mayotte", country_code: "YT", telephone_code: "269" },
#   { name: "Mexico", country_code: "MX", telephone_code: "52" },
#   { name: "Micronesia", country_code: "FM", telephone_code: "691" },
#   { name: "Moldova", country_code: "MD", telephone_code: "373" },
#   { name: "Monaco", country_code: "MC", telephone_code: "377" },
#   { name: "Mongolia", country_code: "MN", telephone_code: "976" },
#   { name: "Montserrat", country_code: "MS", telephone_code: "1664" },
#   { name: "Morocco", country_code: "MA", telephone_code: "212" },
#   { name: "Mozambique", country_code: "MZ", telephone_code: "258" },
#   { name: "Myanmar", country_code: "MN", telephone_code: "95" },
#   { name: "Namibia", country_code: "NA", telephone_code: "264" },
#   { name: "Nauru", country_code: "NR", telephone_code: "674" },
#   { name: "Nepal", country_code: "NP", telephone_code: "977" },
#   { name: "Netherlands", country_code: "NL", telephone_code: "31" },
#   { name: "New Caledonia", country_code: "NC", telephone_code: "687" },
#   { name: "New Zealand", country_code: "NZ", telephone_code: "64" },
#   { name: "Nicaragua", country_code: "NI", telephone_code: "505" },
#   { name: "Niger", country_code: "NE", telephone_code: "227" },
#   { name: "Nigeria", country_code: "NG", telephone_code: "234" },
#   { name: "Niue", country_code: "NU", telephone_code: "683" },
#   { name: "Norfolk Islands", country_code: "NF", telephone_code: "672" },
#   { name: "Northern Marianas", country_code: "NP", telephone_code: "670" },
#   { name: "Norway", country_code: "NO", telephone_code: "47" },
#   { name: "Oman", country_code: "OM", telephone_code: "968" },
#   { name: "Palau", country_code: "PW", telephone_code: "680" },
#   { name: "Panama", country_code: "PA", telephone_code: "507" },
#   { name: "Papua New Guinea", country_code: "PG", telephone_code: "675" },
#   { name: "Paraguay", country_code: "PY", telephone_code: "595" },
#   { name: "Peru", country_code: "PE", telephone_code: "51" },
#   { name: "Philippines", country_code: "PH", telephone_code: "63" },
#   { name: "Poland", country_code: "PL", telephone_code: "48" },
#   { name: "Portugal", country_code: "PT", telephone_code: "351" },
#   { name: "Puerto Rico", country_code: "PR", telephone_code: "1787" },
#   { name: "Qatar", country_code: "QA", telephone_code: "974" },
#   { name: "Reunion", country_code: "RE", telephone_code: "262" },
#   { name: "Romania", country_code: "RO", telephone_code: "40" },
#   { name: "Russia", country_code: "RU", telephone_code: "7" },
#   { name: "Rwanda", country_code: "RW", telephone_code: "250" },
#   { name: "San Marino", country_code: "SM", telephone_code: "378" },
#   { name: "Sao Tome & Principe", country_code: "ST", telephone_code: "239" },
#   { name: "Saudi Arabia", country_code: "SA", telephone_code: "966" },
#   { name: "Senegal", country_code: "SN", telephone_code: "221" },
#   { name: "Serbia", country_code: "CS", telephone_code: "381" },
#   { name: "Seychelles", country_code: "SC", telephone_code: "248" },
#   { name: "Sierra Leone", country_code: "SL", telephone_code: "232" },
#   { name: "Singapore", country_code: "SG", telephone_code: "65" },
#   { name: "Slovak Republic", country_code: "SK", telephone_code: "421" },
#   { name: "Slovenia", country_code: "SI", telephone_code: "386" },
#   { name: "Solomon Islands", country_code: "SB", telephone_code: "677" },
#   { name: "Somalia", country_code: "SO", telephone_code: "252" },
#   { name: "South Africa", country_code: "ZA", telephone_code: "27" },
#   { name: "Spain", country_code: "ES", telephone_code: "34" },
#   { name: "Sri Lanka", country_code: "LK", telephone_code: "94" },
#   { name: "St. Helena", country_code: "SH", telephone_code: "290" },
#   { name: "St. Kitts", country_code: "KN", telephone_code: "1869" },
#   { name: "St. Lucia", country_code: "SC", telephone_code: "1758" },
#   { name: "Sudan", country_code: "SD", telephone_code: "249" },
#   { name: "Suriname", country_code: "SR", telephone_code: "597" },
#   { name: "Swaziland", country_code: "SZ", telephone_code: "268" },
#   { name: "Sweden", country_code: "SE", telephone_code: "46" },
#   { name: "Switzerland", country_code: "CH", telephone_code: "41" },
#   { name: "Syria", country_code: "SI", telephone_code: "963" },
#   { name: "Taiwan", country_code: "TW", telephone_code: "886" },
#   { name: "Tajikstan", country_code: "TJ", telephone_code: "7" },
#   { name: "Thailand", country_code: "TH", telephone_code: "66" },
#   { name: "Togo", country_code: "TG", telephone_code: "228" },
#   { name: "Tonga", country_code: "TO", telephone_code: "676" },
#   { name: "Trinidad & Tobago", country_code: "TT", telephone_code: "1868" },
#   { name: "Tunisia", country_code: "TN", telephone_code: "216" },
#   { name: "Turkey", country_code: "TR", telephone_code: "90" },
#   { name: "Turkmenistan", country_code: "TM", telephone_code: "7" },
#   { name: "Turkmenistan", country_code: "TM", telephone_code: "993" },
#   { name: "Turks & Caicos Islands", country_code: "TC", telephone_code: "1649" },
#   { name: "Tuvalu", country_code: "TV", telephone_code: "688" },
#   { name: "Uganda", country_code: "UG", telephone_code: "256" },
#   { name: "Ukraine", country_code: "UA", telephone_code: "380" },
#   { name: "United Arab Emirates", country_code: "AE", telephone_code: "971" },
#   { name: "Uruguay", country_code: "UY", telephone_code: "598" },
#   { name: "Uzbekistan", country_code: "UZ", telephone_code: "7" },
#   { name: "Vanuatu", country_code: "VU", telephone_code: "678" },
#   { name: "Vatican City", country_code: "VA", telephone_code: "379" },
#   { name: "Venezuela", country_code: "VE", telephone_code: "58" },
#   { name: "Vietnam", country_code: "VN", telephone_code: "84" },
#   { name: "Virgin Islands - British", country_code: "VG", telephone_code: "84" },
#   { name: "Virgin Islands - US", country_code: "VI", telephone_code: "84" },
#   { name: "Wallis & Futuna", country_code: "WF", telephone_code: "681" },
#   { name: "Yemen (North)", country_code: "YE", telephone_code: "969" },
#   { name: "Yemen (South)", country_code: "YE", telephone_code: "967" },
#   { name: "Zambia", country_code: "ZM", telephone_code: "260" },
#   { name: "Zimbabwe", country_code: "ZW", telephone_code: "263" }
# ])

@roles = Role.where("name_en LIKE ?", "Salesman%")
@permissions = Permission.where({ subject_class: "User", name_en: ["new user form", "creation of user", "show user list", "edit user form", "updation of user"] })
@roles.each do |role|
   @permissions.each do |permission|
      RolePermission.create(:role_id => role.id , :permission_id => permission.id )
   end
end
